def print_num():
    num = input("Введите цифру: ")
    print(num)
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()
print_num()